"""Add user_selection_stages and update C_Selection_Stage model

Revision ID: 06f41e09e28a
Revises: 6feb4821ff88
Create Date: 2024-06-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f41e09e28a'
down_revision = '6feb4821ff88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_selection_stages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['c_selection_stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stage_id')
    )
    
    # Сначала добавляем колонку is_default со значением по умолчанию False
    op.execute('ALTER TABLE c_selection_stage ADD COLUMN is_default BOOLEAN DEFAULT false')
    
    # Обновляем существующие записи, устанавливая is_default в True
    op.execute("UPDATE c_selection_stage SET is_default = true")
    
    # Изменяем колонку, делая её NOT NULL
    op.execute('ALTER TABLE c_selection_stage ALTER COLUMN is_default SET NOT NULL')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('c_selection_stage', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    op.drop_table('user_selection_stages')
    # ### end Alembic commands ###
