"""Add cover_letter field to Candidate model

Revision ID: 0aa6e0c272b0
Revises: a9b3b5eef526
Create Date: 2025-05-06 16:10:42.623050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa6e0c272b0'
down_revision = 'a9b3b5eef526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('cover_letter')

    # ### end Alembic commands ###
