"""Add reference tables and encryption

Revision ID: 0cce706ccd0b
Revises: 9f37f42b5a2c
Create Date: 2025-05-02 17:01:57.499479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cce706ccd0b'
down_revision = '9f37f42b5a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_candidate_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_employment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('c_user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('_phone', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('id_c_candidate_status', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_candidates_email')
        batch_op.create_index(batch_op.f('ix_candidates__email'), ['_email'], unique=False)
        batch_op.create_foreign_key(None, 'c_candidate_status', ['id_c_candidate_status'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('_phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_c_gender', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_c_user_status', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avatar_path', sa.Text(), nullable=True))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users__email'), ['_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users__phone'), ['_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id_c_gender'), ['id_c_gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id_c_user_status'), ['id_c_user_status'], unique=False)
        batch_op.create_foreign_key(None, 'c_user_status', ['id_c_user_status'], ['id'])
        batch_op.create_foreign_key(None, 'c_gender', ['id_c_gender'], ['id'])
        batch_op.drop_column('email')

    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_c_employment_type', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_vacancies_id_c_employment_type'), ['id_c_employment_type'], unique=False)
        batch_op.create_foreign_key(None, 'c_employment_type', ['id_c_employment_type'], ['id'])
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vacancies_id_c_employment_type'))
        batch_op.drop_column('id_c_employment_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_id_c_user_status'))
        batch_op.drop_index(batch_op.f('ix_users_id_c_gender'))
        batch_op.drop_index(batch_op.f('ix_users__phone'))
        batch_op.drop_index(batch_op.f('ix_users__email'))
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('id_c_user_status')
        batch_op.drop_column('id_c_gender')
        batch_op.drop_column('_phone')
        batch_op.drop_column('_email')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_candidates__email'))
        batch_op.create_index('ix_candidates_email', ['email'], unique=False)
        batch_op.drop_column('id_c_candidate_status')
        batch_op.drop_column('_phone')
        batch_op.drop_column('_email')

    op.drop_table('c_user_status')
    op.drop_table('c_gender')
    op.drop_table('c_employment_type')
    op.drop_table('c_candidate_status')
    # ### end Alembic commands ###
