"""Add selection_stages_json to Vacancy model

Revision ID: 14ea7dc39ded
Revises: 14e14a8b5f58
Create Date: 2025-05-20 14:06:39.731586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ea7dc39ded'
down_revision = '14e14a8b5f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selection_stages_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_column('selection_stages_json')

    # ### end Alembic commands ###
