"""Add AI generation fields to Vacancy model

Revision ID: 23777cb2a8e1
Revises: 94dec94edbcb
Create Date: 2025-05-15 14:19:52.808494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23777cb2a8e1'
down_revision = '94dec94edbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('ai_generation_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ai_generation_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_generation_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_column('ai_generation_metadata')
        batch_op.drop_column('ai_generation_prompt')
        batch_op.drop_column('ai_generation_date')
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###
