"""empty message

Revision ID: 41945220a023
Revises: f5ab95073aec
Create Date: 2025-05-12 16:33:03.425679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41945220a023'
down_revision = 'f5ab95073aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_values', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_column('company_values')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('resume_data')

    # ### end Alembic commands ###
