"""update user_selection_stages and candidate models

Revision ID: 463ea4a72757
Revises: a5713751978e
Create Date: 2025-05-23 10:52:23.031311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '463ea4a72757'
down_revision = 'a5713751978e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_id', sa.Integer(), nullable=False))
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('tracking_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint('fk_candidate_user_selection_stage', type_='foreignkey')
        batch_op.create_foreign_key('fk_candidate_user_selection_stage', 'user_selection_stages', ['user_id', 'stage_id'], ['user_id', 'stage_id'])
        batch_op.create_foreign_key(None, 'c_selection_stage', ['stage_id'], ['id'])
        batch_op.drop_column('_phone')
        batch_op.drop_column('_email')

    with op.batch_alter_table('user_selection_stages', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_selection_stages_stage_id_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_selection_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_selection_stages_stage_id_key', ['stage_id'])
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('_phone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_candidate_user_selection_stage', type_='foreignkey')
        batch_op.create_foreign_key('fk_candidate_user_selection_stage', 'user_selection_stages', ['user_id', 'id_user_selection_stage'], ['user_id', 'stage_id'])
        batch_op.alter_column('tracking_code',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('stage_id')

    # ### end Alembic commands ###
