"""empty message

Revision ID: 4a1e6f625617
Revises: faa21e692f0c
Create Date: 2025-05-23 11:51:09.777577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1e6f625617'
down_revision = 'faa21e692f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('_phone', sa.Text(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('tracking_code',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_candidates__email'), ['_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidates__phone'), ['_phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates__phone'))
        batch_op.drop_index(batch_op.f('ix_candidates__email'))
        batch_op.alter_column('tracking_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('_phone')
        batch_op.drop_column('_email')

    # ### end Alembic commands ###
