"""Add company and position fields to User model

Revision ID: 65d7f4d23f68
Revises: 0cce706ccd0b
Create Date: 2025-05-05 12:44:54.665261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d7f4d23f68'
down_revision = '0cce706ccd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
