"""Add selection stages table and relation to candidates

Revision ID: 6feb4821ff88
Revises: 23777cb2a8e1
Create Date: 2025-05-15 17:28:14.537914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feb4821ff88'
down_revision = '23777cb2a8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_selection_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_selection_stage', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'c_selection_stage', ['id_selection_stage'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_selection_stage')

    op.drop_table('c_selection_stage')
    # ### end Alembic commands ###
