"""Add additional AI analysis fields to Candidate model

Revision ID: 94dec94edbcb
Revises: 9a6e781afe2e
Create Date: 2025-05-14 12:38:14.187620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dec94edbcb'
down_revision = '9a6e781afe2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_data_consistency', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_answer_quality', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_data_completeness', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis_data')
        batch_op.drop_column('ai_data_completeness')
        batch_op.drop_column('ai_answer_quality')
        batch_op.drop_column('ai_data_consistency')

    # ### end Alembic commands ###
