"""Add structured_resume_data field to Candidate model

Revision ID: 9a6e781afe2e
Revises: add_indexes
Create Date: 2025-05-14 11:44:32.054899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a6e781afe2e'
down_revision = 'add_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_resume_data', sa.JSON(), nullable=True))
        batch_op.drop_index('ix_candidates_created_at')
        batch_op.drop_index('ix_candidates_id_c_candidate_status')
        batch_op.drop_index('ix_candidates_tracking_code')
        batch_op.drop_index('ix_candidates_vacancy_id')
        batch_op.drop_column('resume_data')

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_role')

    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index('ix_vacancies_is_active')
        batch_op.drop_index('ix_vacancies_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index('ix_vacancies_status', ['status'], unique=False)
        batch_op.create_index('ix_vacancies_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_role', ['role'], unique=False)
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index('ix_candidates_vacancy_id', ['vacancy_id'], unique=False)
        batch_op.create_index('ix_candidates_tracking_code', ['tracking_code'], unique=False)
        batch_op.create_index('ix_candidates_id_c_candidate_status', ['id_c_candidate_status'], unique=False)
        batch_op.create_index('ix_candidates_created_at', ['created_at'], unique=False)
        batch_op.drop_column('structured_resume_data')

    # ### end Alembic commands ###
