"""update candidate and user selection stages relationships

Revision ID: a5713751978e
Revises: b62696126f8b
Create Date: 2025-05-23 10:47:30.567105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5713751978e'
down_revision = 'b62696126f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('candidates_id_user_selection_stage_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_candidate_user_selection_stage', 'user_selection_stages', ['user_id', 'id_user_selection_stage'], ['user_id', 'stage_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidate_user_selection_stage', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('candidates_id_user_selection_stage_fkey', 'user_selection_stages', ['id_user_selection_stage'], ['stage_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
