"""remove id_user_selection_stage field

Revision ID: faa21e692f0c
Revises: 463ea4a72757
Create Date: 2025-05-23 10:55:16.190090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa21e692f0c'
down_revision = '463ea4a72757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('id_user_selection_stage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_selection_stage', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
