# Импорт моделей для доступа через app.models
from app.models.user import User
from app.models.vacancy import Vacancy
from app.models.candidate import Candidate
from app.models.notification import Notification
from app.models.system_log import SystemLog
from app.models.c_gender import C_Gender
from app.models.c_education import C_Education
from app.models.c_user_status import C_User_Status
from app.models.c_employment_type import C_Employment_Type
from app.models.skill_category import SkillCategory
from app.models.skill import Skill
from app.models.vacancy_skill import VacancySkill
from app.models.candidate_skill import CandidateSkill
from app.models.industry import Industry
from app.models.vacancy_industry import VacancyIndustry 
from app.models.keyword import Keyword
from app.models.keyword_category import KeywordCategory 
from app.models.c_selection_stage import C_Selection_Stage 
from app.models.user_selection_stages import User_Selection_Stage
from app.models.c_selection_status import C_Selection_Status